theme: null
plugins:
- jekyll-remote-theme

baseurl: "/voxmanifestor-docs"

title: Vox Manifestor Genie
description: Voice-driven manifestation assistant
show_downloads: false

defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default" # Use our custom layout

github:
  is_project_page: true
